drop table users cascade constraints;
drop table billing_info cascade constraints;
drop table market_item cascade constraints;
drop table listing cascade constraints;
drop table game cascade constraints;
drop table item_belongsTo cascade constraints;
drop table transaction_supervises cascade constraints;
drop table administrator cascade constraints;
drop table monitors cascade constraints;
commit;
